
steps:
- script: |
    sudo apt-get update && sudo apt-get install -y wget tar
    JMETER_VERSION=5.6.3
    JMETER_HOME=/opt/jmeter

    if [ -x "$JMETER_HOME/bin/jmeter" ]; then
      echo "JMeter already installed at $JMETER_HOME"
      $JMETER_HOME/bin/jmeter -v
    else
      echo "Installing JMeter $JMETER_VERSION..."
      wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-$JMETER_VERSION.tgz
      tar -xvzf apache-jmeter-$JMETER_VERSION.tgz
      sudo mv apache-jmeter-$JMETER_VERSION $JMETER_HOME
      $JMETER_HOME/bin/jmeter -v
    fi
  displayName: 'Install Apache JMeter (if not exists)'

- script: |
    # Run JMeter test plan (.jmx script)
    /opt/jmeter/bin/jmeter -n -t $(Build.SourcesDirectory)/Azure-auth-poc.jmx \
      -l $(Build.SourcesDirectory)/results.jtl \
      -e -o $(Build.SourcesDirectory)/report

    # Copy report into repo folder for commit
    mkdir -p $(Build.SourcesDirectory)/jmeter-report
    cp -r $(Build.SourcesDirectory)/tests/report/* $(Build.SourcesDirectory)/jmeter-report/
  displayName: 'Run JMeter Test Plan & Copy Report'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/jmeter-report'
    ArtifactName: 'jmeter-report'
    publishLocation: 'Container'
  displayName: 'Publish JMeter HTML Report'
 